import os
import requests
import json
import datetime

def weather_today(city):
    """
    Returns a string with hourly weather forecast for the day.
    Location must be specified as "City".
    """
    # Grab API KEY from local environment
    api_key = os.getenv('OPENWEATHERMAP_API')

    # Url for forecast data in desired City
    url = f'https://api.openweathermap.org/data/2.5/forecast?q={city},us&units=imperial&appid={api_key}'
    r = requests.get(url)

    # Assign data in Python format using json module
    data = json.loads(r.text)
    today = datetime.datetime.today().date() # Grab today's date
    total_forecast = ''
    # Iterate through each item in key 'list'
    for d in data['list']:
        temp_date = datetime.datetime.fromtimestamp(d['dt']) # converts date to YYYY-MM-DD HH:MM:SS format
        if temp_date.date() <= today: # Checks if data is from today as we only want to display today's data
            main_weather = d['weather'][0]['main'] # Extracts weather information
            temperature = int(d['main']['temp']) # Extracts temperatures in fahrenheit
            wind_speed = int(d['wind']['speed']) # Extracts wind speed
            current_forecast = f"Forecast time is: {temp_date} PST, and weather is {main_weather.lower()} in {city}. " \
                               f"The temperature is {temperature} degrees with winds of {wind_speed} mph."
            total_forecast += current_forecast + '\n\n'
    total_forecast += '\n\n' + 'This message was generated by the weatherTimeBot, beep beep boop beep.'
    return total_forecast





